export const UNIT_OPTIONS = [
  { sigla: 'AMPOLA', descricao: 'AMPOLA' },
  { sigla: 'BALDE', descricao: 'BALDE' },
  { sigla: 'BANDEJ', descricao: 'BANDEJA' },
  { sigla: 'BARRA', descricao: 'BARRA' },
  { sigla: 'BISNAG', descricao: 'BISNAGA' },
  { sigla: 'BLOCO', descricao: 'BLOCO' },
  { sigla: 'BOBINA', descricao: 'BOBINA' },
  { sigla: 'BOL', descricao: 'BOLSA' },
  { sigla: 'BOMB', descricao: 'BOMBONA' },
  { sigla: 'CX', descricao: 'CAIXA' },
  { sigla: 'CAPS', descricao: 'CAPSULA' },
  { sigla: 'CART', descricao: 'CARTELA' },
  { sigla: 'CENTO', descricao: 'CENTO' },
  { sigla: 'CONJ', descricao: 'CONJUNTO' },
  { sigla: 'DUZIA', descricao: 'DUZIA' },
  { sigla: 'FRASCO', descricao: 'FRASCO' },
  { sigla: 'GALAO', descricao: 'GALAO' },
  { sigla: 'GRAMA', descricao: 'GRAMA' },
  { sigla: 'HORAS', descricao: 'HORAS' },
  { sigla: 'KIT', descricao: 'KIT' },
  { sigla: 'LATA', descricao: 'LATA' },
  { sigla: 'LITRO', descricao: 'LITRO' },
  { sigla: 'METRO', descricao: 'METRO' },
  { sigla: 'M2', descricao: 'METRO QUADRADO' },
  { sigla: 'M3', descricao: 'METRO CUBICO' },
  { sigla: 'MILHEI', descricao: 'MILHEIRO' },
  { sigla: 'PACOTE', descricao: 'PACOTE' },
  { sigla: 'PAR', descricao: 'PAR' },
  { sigla: 'PEÇA', descricao: 'PEÇA' },
  { sigla: 'RESMA', descricao: 'RESMA' },
  { sigla: 'ROLO', descricao: 'ROLO' },
  { sigla: 'SACO', descricao: 'SACO' },
  { sigla: 'TUBETE', descricao: 'TUBETE' },
  { sigla: 'TUBO', descricao: 'TUBO' },
  { sigla: 'UNID', descricao: 'UNIDADE' },
];

export const BIDDING_MODALITIES = [
  "Pregão Eletrônico",
  "Pregão Presencial",
  "Concorrência",
  "Tomada de Preços",
  "Convite",
  "Concurso",
  "Diálogo Competitivo",
  "Dispensa de Licitação",
  "Inexigibilidade",
  "Credenciamento",
  "Adesão a Ata (Carona)"
];